name: Deploy Flask App

on:
  push:
    branches:
      - main  # Cambia esto por la rama que utilizas para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Stop process using port 5000
        run: |
          sudo lsof -ti:5000 | xargs sudo kill -9 || echo "No process found on port 5000"

      - name: Deploy Flask app
        run: |
          ssh -i "${{ secrets.EC2_SSH_KEY }}" ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/your/app
          # Detén cualquier aplicación Flask en ejecución, si es necesario
          pkill -f 'flask run' || echo "No Flask process found"
          # Navega al directorio de tu proyecto y despliega la nueva versión
          git pull origin main
          nohup python3 app.py > output.log 2>&1 &
          EOF

      - name: Notify deployment
        run: echo "Deployment completed!"
